FROM quay.io/dmartino/serverless-workflow-newsletter-subscription-flow:2.0.0-SNAPSHOT

ENV SUBSCRIPTION_API_URL=http://newsletter-subscription-service.sls-newsletter-dev.svc.cluster.local
ENV POSTGRES_HOST=newsletter-postgres.newsletter-subscription-db
